---
title: "Hw 5"
output: word_notebook
---
```{r include=FALSE}
library(tigris)
library(tidyverse)
library(ggplot2)
library(stringr)
library(broom)
library(purrr)
library(scales)
library(readr)
library(forcats)
library(viridis)
```


```{r}
 
homicides <- read_csv("data/homicide-data.csv")
ca_homi <- homicides %>%
  filter(state == "CA") %>%
  mutate(disposition = str_replace_all(disposition, "Open/No arrest", "unsolved"),
         disposition = str_replace_all(disposition, "Closed without arrest", "unsolved"),
         disposition = str_replace_all(disposition, "Closed by arrest", "solved"))
          
         
         
data("state")
us_state_info <- tibble(state = state.name, 
                            area = state.area,
                            region = state.region)  

ca_counties <- counties(state = "CA", cb = TRUE, class = "sf")

la <- ca_counties %>%
  filter(NAME == "Los Angeles") 
  

laca_homicides <- ca_counties %>%
  rename(city = NAME) %>%
  right_join(ca_homi, by = "city") %>%
  filter(city == "Los Angeles") %>%
  select(city, state, victim_race, lat, lon, disposition, geometry) %>%
  mutate(top3 = fct_lump(victim_race, 3))
```


```{r}
ggplot() +
  geom_sf(data = la, color = "lightgray") + 
  geom_point(data = laca_homicides, aes(x = lon, y = lat, color = top3)) +
  facet_wrap( ~disposition) + 
  theme_dark() +
  scale_colour_brewer(palette = "Set1") +
   theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = "Los Angeles Homicides",
       x = "Longitude",
       y = "Lattitude") 
 



```



